### ISSUE TITLE
When using a custom template and clusterctl needs to be upgraded it appends the output to the template

### ISSUE THREAD

**Issue by jsturtevant** [Azure/azure-capi-cli-extension#137]
#### Issue

Use clusterctl one version behind (1.1.3 in this case) and then generate the template and you will get:

```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: cluster-identity
  namespace: default
spec:
  allowedNamespaces: {}
  clientID: 50b6d626-3907-42f7-b262-95318b9c4602
  clientSecret:
    name: cluster-identity-secret
    namespace: default
  tenantID: 72f988bf-86f1-41af-91ab-2d7cd011db47
  type: ServicePrincipal
[33m
New clusterctl version available: v1.1.3 -> v1.1.4
https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.1.4
[0m
```

This causes the template to fail AzureClusterIdnetity.

### Possible fixes
Workaround is to upgrade the clusterctl version.

The clusterctl logs this to stderr so could not stream that:

[output, err := newVersionChecker(configClient.Variables()).Check()](https://github.com/kubernetes-sigs/cluster-api/blob/5026786ee809c5def466049f5befd2a786fbcefa/cmd/clusterctl/cmd/root.go#L70-L78)
